### PR TITLE
fixes #74

### LINKED ISSUE #74: Empty locale cookie crashes rendering
If you supply an empty locale cookie 🥠 (done by accident  while testing), the application renders an error and is unusable.

The culprit is here https://github.com/fosterfarrell9/mampf/blob/f117f860a277e6219183861605c0aadc17f4fb58/app/controllers/application_controller.rb#L80

This causes the `enforce_available_locales!` to crash, because the locale "" is unknown.

A possible way to mitigate this, would be:
```ruby
if cookies[:locale].in?(I18n.available_locales.map(&:to_s))
  cookie_param = cookies[:locale]
end
I18n.locale = current_user.try(:locale) || locale_param ||
                    cookie_param || I18n.default_locale
```

### PR DESCRIPTION
**Pull request by fosterfarrell9**
This should fix #74 (and make the code a little cleaner along the way).

### CODE REVIEW

File: app/controllers/application_controller.rb [hunk 1]
```diff
@@ -98,4 +95,18 @@ def store_interaction
                                    request.referrer,
                                    study_participant)
   end
+
+  def locale_param
+    return unless params[:locale].in?(available_locales)
+    params[:locale]
+  end
+
+  def cookie_param
```
Comment (henrixapp) [inline app/controllers/application_controller.rb:104]: I think this name `cookie_param` is a not straight forward and confusing, because the method does return the locale and not any cookie param (as I would expect). I would suggest  renaming it to `cookie_locale_param`or `locale_cookie_param`.

**Review by henrixapp — COMMENTED** [review]
Would rename one function.

File: app/controllers/application_controller.rb (hunk 1 above)
Comment (fosterfarrell9) [reply app/controllers/application_controller.rb]: Good point.

**Review by henrixapp — CHANGES_REQUESTED** [review]
The `set_locale`method still called the old `cookie_param`, so the cookie will be never considered.

**Comment by fosterfarrell9** [comment]
Oops.

**Review by henrixapp — APPROVED** [review]
